### ISSUE TITLE
Migrating to 3.0.0 fails with duplicated ReleaseComponents / ReleaseArchitectures

### ISSUE THREAD

**Issue by sdherr** [pulp/pulp_deb#923]
I am in the process of migrating our `pulp_deb-2.20.0-with-patches` installation / db to `pulp_deb-3.0.0`, and I believe I have discovered a migration error related to the removal of the `Release` foreign-key and de-duplicating of `ReleaseComponents` and `ReleaseArchitectures`.

Unfortunately my pure-upstream dev workstation is currently a mess so I have not had a chance to try to replicate the issue with pure-upstream code, but it looks to me like it would still exist. This rework was also a big complicated change I know, so it's entirely possible that I'm missing something.

# Setup:
Simply have two pulp_deb-2.20.0 repos that have duplicate release/component/architectures:
```
Repo1:
  Release(codename="stable", suite="stable", distribution="stable")
    ReleaseComponent(component="main")
    ReleaseArchitecture(architecture="amd64")
Repo2:
  Release(codename="stable", suite="stable", distribution="stable")
    ReleaseComponent(component="main")
    ReleaseArchitecture(architecture="amd64")
```

# Reproduce:
Update to pulp_deb-3.0.0 and run the database migrations.

# Result:
```
+ /usr/local/bin/pulpcore-manager migrate deb 0021
Operations to perform:
  Target specific migration: 0021_remove_release_from_structure_types, from deb
Running migrations:
Traceback (most recent call last):
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/venv/lib/python3.9/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
psycopg.errors.UniqueViolation: could not create unique index "deb_releasearchitecture_architecture_distributio_596756bf_uniq"
DETAIL:  Key (architecture, distribution, codename, suite)=(amd64, stable, stable, stable) is duplicated.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/pulpcore-manager", line 8, in <module>
    sys.exit(manage())
  File "/venv/lib/python3.9/site-packages/pulpcore/app/manage.py", line 11, in manage
    execute_from_command_line(sys.argv)
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/venv/lib/python3.9/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/venv/lib/python3.9/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/venv/lib/python3.9/site-packages/django/core/management/base.py", line 458, in execute
    output = self.handle(*args, **options)
  File "/venv/lib/python3.9/site-packages/django/core/management/base.py", line 106, in wrapper
    res = handle_func(*args, **kwargs)
  File "/venv/lib/python3.9/site-packages/django/core/management/commands/migrate.py", line 356, in handle
    post_migrate_state = executor.migrate(
  File "/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
  File "/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
  File "/venv/lib/python3.9/site-packages/django/db/migrations/executor.py", line 252, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/venv/lib/python3.9/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
  File "/venv/lib/python3.9/site-packages/django/db/migrations/operations/models.py", line 659, in database_forwards
    alter_together(
  File "/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 563, in alter_unique_together
    self.execute(self._create_unique_sql(model, fields))
  File "/venv/lib/python3.9/site-packages/django/db/backends/postgresql/schema.py", line 48, in execute
    return super().execute(sql, None)
  File "/venv/lib/python3.9/site-packages/django/db/backends/base/schema.py", line 201, in execute
    cursor.execute(sql, params)
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/venv/lib/python3.9/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/venv/lib/python3.9/site-packages/django/db/backends/utils.py", line 87, in _execute
    return self.cursor.execute(sql)
  File "/venv/lib/python3.9/site-packages/psycopg/cursor.py", line 737, in execute
    raise ex.with_traceback(None)
django.db.utils.IntegrityError: could not create unique index "deb_releasearchitecture_architecture_distributio_596756bf_uniq"
DETAIL:  Key (architecture, distribution, codename, suite)=(amd64, stable, stable, stable) is duplicated.
```

Perhaps my database is in the duplicate-release failure case that this whole rework was designed to avoid. I see that migration 0025 attempts to de-duplicate `ReleaseComponent` and `ReleaseArchitecture` and update the unique constraint, but of course this failing migration (0021) happens _first_, and we get into a failure state.

If the 0021 migration instead of _altering_ the unique constraints with `AlterUniqueTogether` _removes it entirely_ (by calling `AlterUniqueTogether` with `unique_together=set()` as the _first_ operations in the migration), then things proceed without error and the 0025 migration correctly de-duplicates the `ReleaseComponents` / `ReleaseArchitectures` and re-sets the unique constraints to the new good field list.

I can file a PR that does that if you wish, but given our non-standard db / migration path and how complicated this issue was I thought I'd ask first to see what you think.

**Comment by daviddavis** [comment]
Talking with @sdherr, I think the issue is that we've patched our `Release` models already to include origin/label/etc so we have multiple Release models with overlapping distribution/codename/suite. So this migration is creating `ReleaseComponents` and `ReleaseArchitectures` with duplicate distribution/codename/suite, and I think that's why the uniq constraint is failing.

I think this problem is unique to us probably but I'm still supportive of dropping the unique constraint from the migration since it'll be created in 0025 anyway but I don't have a strong opinion either way.

**Comment by sdherr** [comment]
I'll leave this open so the maintainers have a chance to look / comment. We internally will deal with our migration issues, if this patch provides no value to upstream pulp_deb then I'm fine with dropping it.

**Comment by quba42** [comment]
I do have my eyes on this, but I have not yet found the bandwidth for a detailed look at it.
